#grid(
  columns: (1fr, 1fr),
  gutter: 3pt,  //image("img/boxplot_YEAR.png"),
  //image("img/boxplot_MONTH.png"),
  //image("img/boxplot_DAY.png"),
  //image("img/boxplot_DAY_OF_WEEK.png"),
  image("img/boxplot_FLIGHT_NUMBER.png"),
  image("img/boxplot_SCHEDULED_DEPARTURE.png"),
  image("img/boxplot_DEPARTURE_TIME.png"),
  image("img/boxplot_DEPARTURE_DELAY.png"),
  image("img/boxplot_TAXI_OUT.png"),
  image("img/boxplot_WHEELS_OFF.png"),
  image("img/boxplot_SCHEDULED_TIME.png"),
  image("img/boxplot_ELAPSED_TIME.png"),
  image("img/boxplot_AIR_TIME.png"),
  image("img/boxplot_DISTANCE.png"),
  image("img/boxplot_WHEELS_ON.png"),
  image("img/boxplot_TAXI_IN.png"),
  image("img/boxplot_SCHEDULED_ARRIVAL.png"),
  image("img/boxplot_ARRIVAL_TIME.png"),
  image("img/boxplot_ARRIVAL_DELAY.png"),
  image("img/boxplot_DIVERTED.png"),
  image("img/boxplot_CANCELLED.png"),
  image("img/boxplot_AIR_SYSTEM_DELAY.png"),
  image("img/boxplot_SECURITY_DELAY.png"),
  image("img/boxplot_AIRLINE_DELAY.png"),
  image("img/boxplot_LATE_AIRCRAFT_DELAY.png"),
  image("img/boxplot_WEATHER_DELAY.png")

)
