#grid(
  columns: (1fr, 1fr),
  gutter: 3pt,  //image("img/histogram_YEAR.png"),
  image("img/histogram_MONTH.png"),
  image("img/histogram_DAY.png"),
  image("img/histogram_DAY_OF_WEEK.png"),
  image("img/histogram_AIRLINE.png"),
  image("img/histogram_FLIGHT_NUMBER.png"),
  //image("img/histogram_TAIL_NUMBER.png"),
  //image("img/histogram_ORIGIN_AIRPORT.png"),
  //image("img/histogram_DESTINATION_AIRPORT.png"),
  image("img/histogram_SCHEDULED_DEPARTURE.png"),
  image("img/histogram_DEPARTURE_TIME.png"),
  image("img/histogram_DEPARTURE_DELAY.png"),
  image("img/histogram_TAXI_OUT.png"),
  image("img/histogram_WHEELS_OFF.png"),
  image("img/histogram_SCHEDULED_TIME.png"),
  image("img/histogram_ELAPSED_TIME.png"),
  image("img/histogram_AIR_TIME.png"),
  image("img/histogram_DISTANCE.png"),
  image("img/histogram_WHEELS_ON.png"),
  image("img/histogram_TAXI_IN.png"),
  image("img/histogram_SCHEDULED_ARRIVAL.png"),
  image("img/histogram_ARRIVAL_TIME.png"),
  image("img/histogram_ARRIVAL_DELAY.png"),
  //image("img/histogram_DIVERTED.png"),
  //image("img/histogram_CANCELLED.png"),
  image("img/histogram_CANCELLATION_REASON.png"),
  image("img/histogram_AIR_SYSTEM_DELAY.png"),
  //image("img/histogram_SECURITY_DELAY.png"),
  image("img/histogram_AIRLINE_DELAY.png"),
  image("img/histogram_LATE_AIRCRAFT_DELAY.png"),
  image("img/histogram_WEATHER_DELAY.png")

)